# Generated by Django 4.2.1 on 2023-12-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorders', '0002_remove_order_date_remove_order_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('pending', 'pending'), ('shipped', 'shipped'), ('canceled', 'canceled')], default='pending', max_length=100),
        ),
    ]
