# Generated by Django 4.2.1 on 2023-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorders', '0004_order_created_at_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('delivered', 'delivered'), ('shipped', 'shipped'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
